project:
  type: website
  output-dir: docs

website:
  title: "Bradford Johnson"
  navbar:
    right: 
      - text: "Home"
        file: index.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/

  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: [litera, _variables.scss]
    css: styles.css

editor: visual